// examples/with-vue/src/App.vue
<script setup lang="ts">
import { cropImage } from "@zoom-image/core"
import { useZoomImageClick, useZoomImageHover, useZoomImageMove, useZoomImageWheel } from "@zoom-image/vue"
import { computed, nextTick, ref, watch } from "vue"

const tabs = ref<
  {
    name: string
    href: string
    current: boolean
    value: "wheel" | "hover" | "move" | "click"
  }[]
>([
  { name: "Wheel", href: "#", current: true, value: "wheel" },
  { name: "Hover", href: "#", current: false, value: "hover" },
  { name: "Move", href: "#", current: false, value: "move" },
  { name: "Click", href: "#", current: false, value: "click" },
])

const croppedImage = ref<string>()
const {
  createZoomImage: createZoomImageWheel,
  zoomImageState: zoomImageWheelState,
  setZoomImageState: setZoomImageWheelState,
} = useZoomImageWheel()
const { createZoomImage: createZoomImageHover } = useZoomImageHover()
const { createZoomImage: createZoomImageMove } = useZoomImageMove()
const { createZoomImage: createZoomImageClick } = useZoomImageClick()

const zoomType = computed(() => {
  const found = tabs.value.find((tab) => tab.current)
  return found?.value as "hover" | "wheel" | "move" | "click"
})

const imageWheelContainerRef = ref<HTMLDivElement>()
const imageMoveContainerRef = ref<HTMLDivElement>()
const imageHoverContainerRef = ref<HTMLDivElement>()
const imageClickContainerRef = ref<HTMLDivElement>()
const zoomTargetRef = ref<HTMLDivElement>()

const handleTabClick = (tab: { name: string; href: string; current: boolean }) => {
  tabs.value.forEach((tab) => {
    tab.current = false
  })
  tab.current = true
}

const handleCropWheelZoomImage = async () => {
  croppedImage.value = await cropImage({
    currentZoom: zoomImageWheelState.currentZoom,
    image: (imageWheelContainerRef.value as HTMLDivElement).querySelector("img") as HTMLImageElement,
    positionX: zoomImageWheelState.currentPositionX,
    positionY: zoomImageWheelState.currentPositionY,
    rotation: zoomImageWheelState.currentRotation,
  })
}
const zoomIn = () => {
  setZoomImageWheelState({
    currentZoom: zoomImageWheelState.currentZoom + 0.5,
  })
}
const zoomOut = () => {
  setZoomImageWheelState({
    currentZoom: zoomImageWheelState.currentZoom - 0.5,
  })
}

const rotate = () => {
  setZoomImageWheelState({
    currentRotation: zoomImageWheelState.currentRotation + 90,
  })

  if (croppedImage.value) {
    handleCropWheelZoomImage()
  }
}

const croppedImageClasses = computed(() => {
  if (zoomImageWheelState.currentRotation === 90 || zoomImageWheelState.currentRotation === 270) {
    return "h-[200px] w-[300px]"
  } else {
    return "h-[300px] w-[200px]"
  }
})

watch(
  zoomType,
  async () => {
    croppedImage.value = ""
    await nextTick()

    if (zoomType.value === "hover") {
      createZoomImageHover(imageHoverContainerRef.value as HTMLDivElement, {
        zoomImageSource: "/sample.avif",
        customZoom: { width: 300, height: 500 },
        zoomTarget: zoomTargetRef.value as HTMLDivElement,
        scale: 2,
      })
    }

    if (zoomType.value === "wheel") {
      createZoomImageWheel(imageWheelContainerRef.value as HTMLDivElement)
    }

    if (zoomType.value === "move") {
      createZoomImageMove(imageMoveContainerRef.value as HTMLDivElement, {
        zoomImageSource: "/sample.avif",
      })
    }

    if (zoomType.value === "click") {
      createZoomImageClick(imageClickContainerRef.value as HTMLDivElement, {
        zoomImageSource: "/sample.avif",
      })
    }
  },
  { immediate: true },
)
</script>

<template>
  <div class="p-4 font-sans">
    <nav class="flex space-x-4 pb-4" aria-label="Tabs">
      <a
        v-for="tab in tabs"
        @click="handleTabClick(tab)"
        :key="tab.name"
        :href="tab.href"
        :class="[
          tab.current ? 'text-dark-700 bg-gray-100' : 'text-dark-500 hover:text-dark-700',
          'decoration-none rounded-md px-3 py-2 text-sm font-medium',
        ]"
        :aria-current="tab.current ? 'page' : undefined"
        >{{ tab.name }}</a
      >
    </nav>

    <div class="space-y-4" v-if="zoomType === 'wheel'">
      <p>Scroll / Pinch inside the image to see zoom in-out effect</p>
      <p>Current zoom: {{ `${Math.round(zoomImageWheelState.currentZoom * 100)}%` }}</p>
      <div class="flex items-center gap-4">
        <div class="mt-1 grid h-[300px] w-[300px] place-content-center bg-black">
          <div ref="imageWheelContainerRef" class="h-[300px] w-[200px] cursor-crosshair duration-500">
            <img class="h-full w-full" alt="Large Pic" src="/sample.avif" />
          </div>
        </div>
        <img :src="croppedImage" v-if="!!croppedImage" :class="croppedImageClasses" alt="Cropped placeholder" />
      </div>

      <div class="flex space-x-2">
        <button @click="zoomIn" class="text-dark-500 rounded bg-gray-100 p-2 text-sm font-medium">Zoom in</button>
        <button @click="zoomOut" class="text-dark-500 rounded bg-gray-100 p-2 text-sm font-medium">Zoom out</button>
        <button class="text-dark-500 rounded bg-gray-100 p-2 text-sm font-medium" @click="handleCropWheelZoomImage">
          Crop image
        </button>
        <button @click="rotate" class="text-dark-500 rounded bg-gray-100 p-2 text-sm font-medium">Rotate</button>
      </div>
    </div>

    <div class="space-y-4" v-if="zoomType === 'hover'">
      <p>Hover inside the image to see zoom effect</p>
      <div ref="imageHoverContainerRef" class="relative mt-1 flex h-[300px] w-[200px] items-start">
        <img class="h-full w-full" alt="Small Pic" src="/sample.avif" />
        <div ref="zoomTargetRef" class="absolute left-[350px]"></div>
      </div>
    </div>

    <div class="space-y-4" v-if="zoomType === 'move'">
      <p>Move mouse inside the image to see zoom effect</p>
      <div ref="imageMoveContainerRef" class="relative mt-1 h-[300px] w-[200px] cursor-crosshair overflow-hidden">
        <img class="h-full w-full" alt="Large Pic" src="/sample.avif" />
      </div>
    </div>

    <div class="space-y-4" v-if="zoomType === 'click'">
      <p>Click inside the image to see zoom effect</p>
      <div ref="imageClickContainerRef" class="relative mt-1 h-[300px] w-[200px] cursor-crosshair overflow-hidden">
        <img class="h-full w-full" alt="Large Pic" src="/sample.avif" />
      </div>
    </div>
  </div>
</template>

// examples/with-react/src/App.tsx
import { cropImage } from "@zoom-image/core"
import { useZoomImageClick, useZoomImageHover, useZoomImageMove, useZoomImageWheel } from "@zoom-image/react"
import { useEffect, useMemo, useRef, useState } from "react"

function App() {
  const [tabs, setTabs] = useState<
    {
      name: string
      href: string
      current: boolean
      value: "wheel" | "hover" | "move" | "click"
    }[]
  >([
    { name: "Wheel", href: "#", current: true, value: "wheel" },
    { name: "Hover", href: "#", current: false, value: "hover" },
    { name: "Move", href: "#", current: false, value: "move" },
    { name: "Click", href: "#", current: false, value: "click" },
  ])

  const zoomType = useMemo(() => tabs.find((tab) => tab.current)?.value, [tabs])
  const imageWheelContainerRef = useRef<HTMLDivElement>(null)
  const imageHoverContainerRef = useRef<HTMLDivElement>(null)
  const imageMoveContainerRef = useRef<HTMLDivElement>(null)
  const imageClickContainerRef = useRef<HTMLDivElement>(null)
  const zoomTargetRef = useRef<HTMLDivElement>(null)
  const [croppedImage, setCroppedImage] = useState<string | null>(null)

  const {
    createZoomImage: createZoomImageWheel,
    zoomImageState: zoomImageWheelState,
    setZoomImageState: setZoomImageWheelState,
  } = useZoomImageWheel()
  const { createZoomImage: createZoomImageHover } = useZoomImageHover()
  const { createZoomImage: createZoomImageMove } = useZoomImageMove()
  const { createZoomImage: createZoomImageClick } = useZoomImageClick()

  async function handleCropWheelZoomImage() {
    setCroppedImage(
      await cropImage({
        currentZoom: zoomImageWheelState.currentZoom,
        image: imageWheelContainerRef.current?.querySelector("img") as HTMLImageElement,
        positionX: zoomImageWheelState.currentPositionX,
        positionY: zoomImageWheelState.currentPositionY,
        rotation: zoomImageWheelState.currentRotation,
      }),
    )
  }

  const makeHandleTabClick = (tab: (typeof tabs)[0]) => () => {
    setTabs(
      tabs.map((t) => {
        if (t.name === tab.name) {
          return { ...t, current: true }
        } else {
          return { ...t, current: false }
        }
      }),
    )
  }

  const croppedImageClasses = useMemo(() => {
    if (zoomImageWheelState.currentRotation % 180 === 90) {
      return "h-[200px] w-[300px]"
    } else {
      return "h-[300px] w-[200px]"
    }
  }, [zoomImageWheelState.currentRotation])

  useEffect(() => {
    setCroppedImage("")
    if (zoomType === "wheel") {
      const imageContainer = imageWheelContainerRef.current as HTMLDivElement
      createZoomImageWheel(imageContainer)
    }

    if (zoomType === "hover") {
      const imageContainer = imageHoverContainerRef.current as HTMLDivElement
      const zoomTarget = zoomTargetRef.current as HTMLDivElement
      createZoomImageHover(imageContainer, {
        zoomImageSource: "/sample.avif",
        customZoom: { width: 300, height: 500 },
        zoomTarget,
        scale: 2,
      })
    }

    if (zoomType === "move") {
      const imageContainer = imageMoveContainerRef.current as HTMLDivElement
      createZoomImageMove(imageContainer, {
        zoomImageSource: "/sample.avif",
      })
    }

    if (zoomType === "click") {
      const imageContainer = imageClickContainerRef.current as HTMLDivElement
      createZoomImageClick(imageContainer, {
        zoomImageSource: "/sample.avif",
      })
    }
  }, [zoomType])

  useEffect(() => {
    if (croppedImage) {
      handleCropWheelZoomImage()
    }
  }, [zoomImageWheelState.currentRotation])

  function zoomInWheel() {
    setZoomImageWheelState({
      currentZoom: zoomImageWheelState.currentZoom + 0.5,
    })
  }

  function zoomOutWheel() {
    setZoomImageWheelState({
      currentZoom: zoomImageWheelState.currentZoom - 0.5,
    })
  }

  function rotate() {
    setZoomImageWheelState({
      currentRotation: zoomImageWheelState.currentRotation + 90,
    })
  }

  return (
    <div className="p-4 font-sans">
      <nav className="flex space-x-4 pb-4" aria-label="Tabs">
        {tabs.map((tab) => {
          return (
            <a
              onClick={makeHandleTabClick(tab)}
              key={tab.name}
              href={tab.href}
              className={
                "decoration-none rounded-md px-3 py-2 text-sm font-medium " +
                (tab.current ? "bg-gray-100 text-gray-700" : "text-gray-500 hover:text-gray-700")
              }
              aria-current={tab.current ? "page" : undefined}
            >
              {tab.name}
            </a>
          )
        })}
      </nav>

      {zoomType === "wheel" && (
        <div className="space-y-4">
          <p>Current zoom: {`${Math.round(zoomImageWheelState.currentZoom * 100)}%`}</p>
          <p>Scroll inside the image to see zoom in-out effect</p>
          <div className="flex items-center gap-4">
            <div className="mt-1 grid h-[300px] w-[300px] place-content-center bg-black">
              <div ref={imageWheelContainerRef} className="h-[300px] w-[200px] cursor-crosshair duration-500">
                <img className="h-full w-full" alt="Large Pic" src="/sample.avif" />
              </div>
            </div>
            {croppedImage && <img src={croppedImage} className={croppedImageClasses} alt="Cropped placeholder" />}
          </div>

          <div className="flex space-x-2">
            <button onClick={zoomInWheel} className="text-dark-500 rounded bg-gray-100 p-2 text-sm font-medium">
              Zoom in
            </button>
            <button onClick={zoomOutWheel} className="text-dark-500 rounded bg-gray-100 p-2 text-sm font-medium">
              Zoom out
            </button>
            <button
              className="text-dark-500 rounded bg-gray-100 p-2 text-sm font-medium"
              onClick={handleCropWheelZoomImage}
            >
              Crop image
            </button>

            <button onClick={rotate} className="text-dark-500 rounded bg-gray-100 p-2 text-sm font-medium">
              Rotate
            </button>
          </div>
        </div>
      )}

      {zoomType === "hover" && (
        <>
          <p>Hover inside the image to see zoom effect</p>
          <div ref={imageHoverContainerRef} className="relative flex h-[300px] w-[200px] items-start">
            <img className="h-full w-full" alt="Small Pic" src="/sample.avif" />
            <div ref={zoomTargetRef} className="absolute left-[350px]"></div>
          </div>
        </>
      )}

      {zoomType === "move" && (
        <>
          <p>Move mouse inside the image to see zoom effect</p>
          <div ref={imageMoveContainerRef} className="relative h-[300px] w-[200px] cursor-crosshair overflow-hidden">
            <img className="h-full w-full" alt="Large Pic" src="/sample.avif" />
          </div>
        </>
      )}

      {zoomType === "click" && (
        <>
          <p>Click inside the image to see zoom effect</p>
          <div ref={imageClickContainerRef} className="relative h-[300px] w-[200px] cursor-crosshair overflow-hidden">
            <img className="h-full w-full" alt="Large Pic" src="/sample.avif" />
          </div>
        </>
      )}
    </div>
  )
}

export default App
