// packages/solid/src/useZoomImageWheel.ts
import { createZoomImageWheel as _createZoomImageWheel, ZoomImageWheelStateUpdate } from "@zoom-image/core"
import { onCleanup } from "solid-js"
import { createStore } from "solid-js/store"

import type { ZoomImageWheelState } from "@zoom-image/core"

export function useZoomImageWheel() {
  let result: ReturnType<typeof _createZoomImageWheel> | undefined
  const [zoomImageState, updateZoomImageState] = createStore<ZoomImageWheelState>({
    currentZoom: 1,
    enable: true,
    currentPositionX: 0,
    currentPositionY: 0,
  })

  const createZoomImage = (...arg: Parameters<typeof _createZoomImageWheel>) => {
    result?.cleanup()
    result = _createZoomImageWheel(...arg)
    updateZoomImageState(result.getState())

    result.subscribe(({ state }) => {
      updateZoomImageState(state)
    })
  }

  onCleanup(() => {
    result?.cleanup()
  })

  const setZoomImageState = (state: ZoomImageWheelStateUpdate) => {
    result?.setState(state)
  }

  return {
    createZoomImage,
    zoomImageState,
    setZoomImageState,
  }
}

// packages/qwik/src/useZoomImageWheel.ts
import { useSignal, useStore, useVisibleTask$, $, noSerialize } from "@builder.io/qwik"
import { createZoomImageWheel as _createZoomImageWheel, ZoomImageWheelStateUpdate } from "@zoom-image/core"

import type { ZoomImageWheelState } from "@zoom-image/core"

type CreateZoomImageWheelResult = ReturnType<typeof _createZoomImageWheel>

export function useZoomImageWheel() {
  const result = useSignal<CreateZoomImageWheelResult>()
  const zoomImageState = useStore<ZoomImageWheelState>({
    currentPositionX: -1,
    currentPositionY: -1,
    currentZoom: -1,
    enable: false,
  })

  useVisibleTask$(({ cleanup }) => {
    cleanup(() => {
      result.value?.cleanup()
    })
  })

  const createZoomImage = $((...arg: Parameters<typeof _createZoomImageWheel>) => {
    result.value?.cleanup()
    result.value = noSerialize(_createZoomImageWheel(...arg)) as CreateZoomImageWheelResult
    const currentState = result.value.getState()
    zoomImageState.currentPositionX = currentState.currentPositionX
    zoomImageState.currentPositionY = currentState.currentPositionY
    zoomImageState.currentZoom = currentState.currentZoom
    zoomImageState.enable = currentState.enable

    result.value.subscribe((state) => {
      zoomImageState.currentPositionX = state.currentPositionX
      zoomImageState.currentPositionY = state.currentPositionY
      zoomImageState.currentZoom = state.currentZoom
      zoomImageState.enable = state.enable
    })
  })

  const setZoomImageState = $((updateState: ZoomImageWheelStateUpdate) => {
    result.value?.setState(updateState)
  })

  return {
    createZoomImage,
    zoomImageState,
    setZoomImageState,
  }
}
