// packages/solid/src/useZoomImageHover.ts
import { onCleanup } from "solid-js"
import { createZoomImageHover as _createZoomImageHover, ZoomImageHoverStateUpdate } from "@zoom-image/core"

import type { ZoomImageHoverState } from "@zoom-image/core"
import { createStore } from "solid-js/store"

export function useZoomImageHover() {
  let result: ReturnType<typeof _createZoomImageHover> | undefined
  const [zoomImageState, updateZoomImageState] = createStore<ZoomImageHoverState>({
    enabled: false,
    zoomedImgStatus: "idle",
  })

  const createZoomImage = (...arg: Parameters<typeof _createZoomImageHover>) => {
    result?.cleanup()
    result = _createZoomImageHover(...arg)
    updateZoomImageState(result.getState())

    result.subscribe(({ state }) => {
      updateZoomImageState(state)
    })
  }

  onCleanup(() => {
    result?.cleanup()
  })

  const setZoomImageState = (updatedState: ZoomImageHoverStateUpdate) => {
    result?.setState(updatedState)
  }

  return {
    createZoomImage,
    zoomImageState,
    setZoomImageState,
  }
}

// packages/qwik/src/useZoomImageHover.ts
import { useSignal, useStore, useVisibleTask$ } from "@builder.io/qwik"
import { createZoomImageHover as _createZoomImageHover, ZoomImageHoverStateUpdate } from "@zoom-image/core"

import type { ZoomImageHoverState } from "@zoom-image/core"

export function useZoomImageHover() {
  const result = useSignal<ReturnType<typeof _createZoomImageHover>>()
  const zoomImageState = useStore<ZoomImageHoverState>({
    enabled: false,
    zoomedImgStatus: "idle",
  })

  useVisibleTask$(({ cleanup }) => {
    cleanup(() => {
      result.value?.cleanup()
    })
  })

  const createZoomImage = (...arg: Parameters<typeof _createZoomImageHover>) => {
    result.value?.cleanup()
    result.value = _createZoomImageHover(...arg)
    const currentState = result.value.getState()
    zoomImageState.enabled = currentState.enabled
    zoomImageState.zoomedImgStatus = currentState.zoomedImgStatus

    result.value.subscribe((state) => {
      zoomImageState.enabled = state.enabled
      zoomImageState.zoomedImgStatus = state.zoomedImgStatus
    })
  }

  const setZoomImageState = (state: ZoomImageHoverStateUpdate) => {
    result.value?.setState(state)
  }

  return {
    createZoomImage,
    zoomImageState,
    setZoomImageState,
  }
}
