// packages/solid/src/useZoomImageHover.ts
import { onCleanup } from "solid-js"
import { createZoomImageHover as _createZoomImageHover, ZoomImageHoverStateUpdate } from "@zoom-image/core"

import type { ZoomImageHoverState } from "@zoom-image/core"
import { createStore } from "solid-js/store"

export function useZoomImageHover() {
  let result: ReturnType<typeof _createZoomImageHover> | undefined
  const [zoomImageState, updateZoomImageState] = createStore<ZoomImageHoverState>({
    enabled: false,
    zoomedImgStatus: "idle",
  })

  const createZoomImage = (...arg: Parameters<typeof _createZoomImageHover>) => {
    result?.cleanup()
    result = _createZoomImageHover(...arg)
    updateZoomImageState(result.getState())

    result.subscribe(({ state }) => {
      updateZoomImageState(state)
    })
  }

  onCleanup(() => {
    result?.cleanup()
  })

  const setZoomImageState = (updatedState: ZoomImageHoverStateUpdate) => {
    result?.setState(updatedState)
  }

  return {
    createZoomImage,
    zoomImageState,
    setZoomImageState,
  }
}

// packages/react/src/useZoomImageHover.ts
import { useCallback, useEffect, useRef, useState } from "react"
import { createZoomImageHover as _createZoomImageHover } from "@zoom-image/core"
import { noop } from "./shared"

import type { ZoomImageHoverState } from "@zoom-image/core"

export function useZoomImageHover() {
  const result = useRef<ReturnType<typeof _createZoomImageHover>>()
  const [zoomImageState, updateZoomImageState] = useState<ZoomImageHoverState>({
    enabled: false,
    zoomedImgStatus: "idle",
  })

  const createZoomImage = useCallback((...arg: Parameters<typeof _createZoomImageHover>) => {
    result.current?.cleanup()
    result.current = _createZoomImageHover(...arg)
    updateZoomImageState(result.current.getState())

    result.current.subscribe(({ state }) => {
      updateZoomImageState(state)
    })
  }, [])

  useEffect(() => {
    return () => {
      result.current?.cleanup()
    }
  }, [])

  return {
    createZoomImage,
    zoomImageState,
    setZoomImageState: result.current?.setState ?? noop,
  }
}
